from datetime import timedelta
from decimal import Decimal
from unittest.mock import patch

from abdm.models import AbhaNumber, HealthFacility, PaymentOrder
from abdm.models.payment_order import PaymentOrderStatus
from abdm.service.helper import uuid
from abdm.utils import user as abdm_user
from care_sbiepay.utils import crypto
from django.test import SimpleTestCase
from model_bakery import baker

from care.emr.models.invoice import Invoice
from care.emr.models.payment_reconciliation import PaymentReconciliation
from care.emr.resources.invoice.spec import InvoiceStatusOptions
from care.utils.tests.base import CareAPITestBase
from care.utils.time_util import care_now
from care_sbiepay import payments
from care_sbiepay import provider as sbiepay_provider
from care_sbiepay.models import SbiEpayPayment
from care_sbiepay.settings import plugin_settings as settings


class TestSbiEpayCrypto(SimpleTestCase):
    def test_encrypt_decrypt_roundtrip(self):
        key = "/IIvvWMcy5ls/V2hCNZ5/Q=="
        enc = crypto.encrypt(key, "hello world")
        self.assertEqual(crypto.decrypt(key, enc), "hello world")


class SbiEpayTestBase(CareAPITestBase):
    def setUp(self):
        # cached across tests but each test rolls back; reset to avoid stale FK.
        abdm_user.ABDM_USER = None
        self.user = self.create_super_user()
        self.facility = self.create_facility(self.user)
        self.health_facility = baker.make(
            HealthFacility, facility=self.facility, hf_id="TEST_HIP"
        )
        self.patient = self.create_patient(phone_number="+919999999999")
        self.abha_number = baker.make(
            AbhaNumber,
            patient=self.patient,
            health_id="testpatient@sbx",
            abha_number="91123456789012",
        )
        self.account = baker.make(
            "emr.Account", facility=self.facility, patient=self.patient
        )

    def make_invoice(self, number="INV-SBI"):
        return baker.make(
            Invoice,
            facility=self.facility,
            patient=self.patient,
            account=self.account,
            status=InvoiceStatusOptions.issued.value,
            total_gross=Decimal(100),
            number=number,
        )

    def make_order(self):
        return PaymentOrder.objects.create(
            open_order_request_id=uuid(),
            abha_number=self.abha_number,
            health_facility=self.health_facility,
            invoice=self.make_invoice("INV-SBI-REC"),
            order_number="sbiorder123",
            status=PaymentOrderStatus.PAYMENT_INITIATED,
        )


class TestSbiEpayProvider(SbiEpayTestBase):
    @patch("care_sbiepay.provider.client.create_payment_link")
    def test_create_payment_link(self, mock_create):
        mock_create.return_value = {
            "merchOrderNo": "abc123",
            "amount": 100,
            "paymentUrl": "https://epay.sbiuat.bank.in/secure/epayPayment.jsp?enctoken=xyz",
        }

        result = sbiepay_provider.SbiEpayProvider().create_payment_link(
            self.make_invoice()
        )

        self.assertEqual(
            result["payment_url"],
            "https://epay.sbiuat.bank.in/secure/epayPayment.jsp?enctoken=xyz",
        )
        self.assertEqual(result["payment_link_id"], result["payment_url"])
        self.assertLessEqual(len(result["order_number"]), 15)
        self.assertTrue(result["order_number"].isalnum())
        # order ref is generated by us, not passed straight through
        self.assertEqual(
            mock_create.call_args.kwargs["merch_order_no"], result["order_number"]
        )


class TestSbiEpayReconcile(SbiEpayTestBase):
    @patch("abdm.signals.scan_pay.scan_pay_notify.delay")
    @patch("care_sbiepay.provider.client.status_query")
    def test_reconcile_marks_paid_and_notifies(self, mock_status, mock_task):
        mock_status.return_value = {
            "Response Status": "SUCCESS",
            "SBIePayRefID/ATRN": "ATRN123",
        }
        order = self.make_order()

        sbiepay_provider.SbiEpayProvider().reconcile_order(order)

        order.refresh_from_db()
        self.assertEqual(order.status, PaymentOrderStatus.SUCCESS)
        self.assertEqual(order.transaction_id, "ATRN123")
        self.assertTrue(
            PaymentReconciliation.objects.filter(
                target_invoice=order.invoice
            ).exists()
        )
        mock_task.assert_called_once()

    @patch("abdm.signals.scan_pay.scan_pay_notify.delay")
    @patch("care_sbiepay.provider.client.status_query")
    def test_reconcile_ignores_unpaid(self, mock_status, mock_task):
        mock_status.return_value = {"Response Status": "NA"}
        order = self.make_order()

        sbiepay_provider.SbiEpayProvider().reconcile_order(order)

        order.refresh_from_db()
        self.assertEqual(order.status, PaymentOrderStatus.PAYMENT_INITIATED)
        self.assertFalse(
            PaymentReconciliation.objects.filter(
                target_invoice=order.invoice
            ).exists()
        )
        mock_task.assert_not_called()

    @patch("abdm.signals.scan_pay.scan_pay_notify.delay")
    def test_push_marks_paid_and_notifies(self, mock_task):
        order = self.make_order()

        sbiepay_provider.reconcile_abdm_push(
            {
                "merch_order_no": "sbiorder123",
                "status": "SUCCESS",
                "atrn": "ATRN999",
                "bank_ref_number": "BR123",
            }
        )

        order.refresh_from_db()
        self.assertEqual(order.status, PaymentOrderStatus.SUCCESS)
        self.assertEqual(order.transaction_id, "ATRN999")
        self.assertTrue(
            PaymentReconciliation.objects.filter(
                target_invoice=order.invoice
            ).exists()
        )
        mock_task.assert_called_once()

    @patch("abdm.signals.scan_pay.scan_pay_notify.delay")
    def test_push_ignores_unpaid(self, mock_task):
        order = self.make_order()

        sbiepay_provider.reconcile_abdm_push(
            {"merch_order_no": "sbiorder123", "status": "FAILED"}
        )

        order.refresh_from_db()
        self.assertEqual(order.status, PaymentOrderStatus.PAYMENT_INITIATED)
        mock_task.assert_not_called()


class TestSbiEpayStandalonePayment(SbiEpayTestBase):
    @patch("care_sbiepay.payments.client.create_payment_link")
    def test_create_payment_persists_record(self, mock_create):
        mock_create.return_value = {
            "paymentUrl": "https://epay.sbiuat.bank.in/secure/epayPayment.jsp?enctoken=xyz",
        }

        payment = payments.create_payment(self.make_invoice())

        self.assertEqual(payment.status, SbiEpayPayment.Status.CREATED)
        self.assertEqual(
            payment.payment_url,
            "https://epay.sbiuat.bank.in/secure/epayPayment.jsp?enctoken=xyz",
        )
        self.assertLessEqual(len(payment.order_number), 15)
        self.assertEqual(
            mock_create.call_args.kwargs["merch_order_no"], payment.order_number
        )

    @patch("care_sbiepay.payments.rebalance_account_task.delay")
    def test_push_reconciles_standalone_payment(self, mock_rebalance):
        invoice = self.make_invoice("INV-STANDALONE")
        payment = SbiEpayPayment.objects.create(
            order_number="standalone123",
            invoice=invoice,
            amount=invoice.total_gross,
        )

        payments.reconcile_push(
            {
                "merch_order_no": "standalone123",
                "status": "SUCCESS",
                "atrn": "ATRN555",
            }
        )

        payment.refresh_from_db()
        self.assertEqual(payment.status, SbiEpayPayment.Status.PAID)
        self.assertEqual(payment.reference, "ATRN555")
        self.assertTrue(
            PaymentReconciliation.objects.filter(target_invoice=invoice).exists()
        )
        mock_rebalance.assert_called_once()

    @patch("care_sbiepay.payments.rebalance_account_task.delay")
    def test_push_keeps_pending_payment_created(self, mock_rebalance):
        invoice = self.make_invoice("INV-STANDALONE-2")
        payment = SbiEpayPayment.objects.create(
            order_number="standalone456",
            invoice=invoice,
            amount=invoice.total_gross,
        )

        payments.reconcile_push(
            {"merch_order_no": "standalone456", "status": "PENDING"}
        )

        payment.refresh_from_db()
        self.assertEqual(payment.status, SbiEpayPayment.Status.CREATED)
        self.assertFalse(
            PaymentReconciliation.objects.filter(target_invoice=invoice).exists()
        )
        mock_rebalance.assert_not_called()

    def test_push_marks_failed_standalone_payment(self):
        invoice = self.make_invoice("INV-STANDALONE-3")
        payment = SbiEpayPayment.objects.create(
            order_number="standalone789",
            invoice=invoice,
            amount=invoice.total_gross,
        )

        payments.reconcile_push(
            {"merch_order_no": "standalone789", "status": "FAILURE"}
        )

        payment.refresh_from_db()
        self.assertEqual(payment.status, SbiEpayPayment.Status.FAILED)
        self.assertFalse(
            PaymentReconciliation.objects.filter(target_invoice=invoice).exists()
        )

    def test_push_returns_false_for_unknown_order(self):
        self.assertFalse(
            payments.reconcile_push({"merch_order_no": "unknown", "status": "SUCCESS"})
        )

    @patch("care_sbiepay.payments.rebalance_account_task.delay")
    @patch("care_sbiepay.payments.client.status_query")
    def test_poll_reconciles_paid_pending_payment(self, mock_status, mock_rebalance):
        mock_status.return_value = {
            "Response Status": "SUCCESS",
            "SBIePayRefID/ATRN": "ATRN777",
        }
        invoice = self.make_invoice("INV-POLL")
        payment = SbiEpayPayment.objects.create(
            order_number="pollorder123",
            invoice=invoice,
            amount=invoice.total_gross,
        )

        payments.poll_pending_payments()

        payment.refresh_from_db()
        self.assertEqual(payment.status, SbiEpayPayment.Status.PAID)
        self.assertEqual(payment.reference, "ATRN777")
        self.assertTrue(
            PaymentReconciliation.objects.filter(target_invoice=invoice).exists()
        )

    @patch("care_sbiepay.payments.client.status_query")
    def test_poll_expires_stale_payment(self, mock_status):
        invoice = self.make_invoice("INV-EXPIRE")
        payment = SbiEpayPayment.objects.create(
            order_number="staleorder123",
            invoice=invoice,
            amount=invoice.total_gross,
        )
        stale = care_now() - timedelta(seconds=settings.SBI_EPAY_PAYMENT_MAX_AGE + 60)
        SbiEpayPayment.objects.filter(pk=payment.pk).update(created_date=stale)

        payments.poll_pending_payments()

        payment.refresh_from_db()
        self.assertEqual(payment.status, SbiEpayPayment.Status.EXPIRED)
        mock_status.assert_not_called()
