# Generated by Django 6.0 on 2026-09-29 08:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_sbiepay', '0001_initial'),
        ('facility', '0485_rename_patientmobileotp_mobileotp'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbiEpayMerchant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('merchant_code', models.CharField(max_length=255)),
                ('merchant_key', models.CharField(max_length=255)),
                ('is_enabled', models.BooleanField(default=True)),
                ('facility', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='facility.facility', to_field='external_id')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
