# Generated by Django 6.0 on 2026-09-29 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_sbiepay', '0002_sbiepaymerchant'),
    ]

    operations = [
        migrations.AddField(
            model_name='sbiepaypayment',
            name='expires_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
    ]
