# Generated by Django 6.0 on 2026-09-29 10:46

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('care_sbiepay', '0003_payment_expires_at'),
        ('emr', '0080_alter_activitydefinition_category_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SbiEpayPushEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(db_index=True, default=uuid.uuid4, unique=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, db_index=True, null=True)),
                ('modified_date', models.DateTimeField(auto_now=True, db_index=True, null=True)),
                ('deleted', models.BooleanField(db_index=True, default=False)),
                ('payload_hash', models.CharField(max_length=64, unique=True)),
                ('merchant_code', models.CharField(blank=True, default='', max_length=255)),
                ('order_number', models.CharField(blank=True, db_index=True, default='', max_length=100)),
                ('gateway_status', models.CharField(blank=True, default='', max_length=64)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True)),
                ('currency', models.CharField(blank=True, default='', max_length=16)),
                ('reference', models.CharField(blank=True, default='', max_length=255)),
                ('raw_form', models.JSONField(blank=True, default=dict)),
                ('decoded', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('received', 'Received'), ('processed', 'Processed'), ('ignored', 'Ignored'), ('failed', 'Failed')], db_index=True, default='received', max_length=16)),
                ('attempts', models.PositiveSmallIntegerField(default=0)),
                ('error_message', models.TextField(blank=True, default='')),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='sbiepaypayment',
            name='needs_review',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='sbiepaypayment',
            name='paid_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='sbiepaypayment',
            name='reconciliation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sbiepay_payment', to='emr.paymentreconciliation'),
        ),
        migrations.AddField(
            model_name='sbiepaypayment',
            name='review_reason',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='sbiepaypayment',
            name='status',
            field=models.CharField(choices=[('created', 'Created'), ('paid', 'Paid'), ('failed', 'Failed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('superseded', 'Superseded')], default='created', max_length=16),
        ),
        migrations.AddConstraint(
            model_name='sbiepaypayment',
            constraint=models.UniqueConstraint(condition=models.Q(('status', 'paid'), models.Q(('reference', ''), _negated=True)), fields=('reference',), name='sbiepay_unique_paid_reference'),
        ),
    ]
